title:              MONEYGRAVITY
email:              yoox6260@mylaurier.ca
description:        Investment Blog
author:             Alex Yoo
baseurl:            "/"
url:                "https://moneygravity.ca"

# Social Profiles
twitter_username:   yoalex820
github_username:    yoalex820
facebook_username:  yoalex820
instagram_username:  yoalex820
linkedin_username: yoalex820

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
